name: Publish Vizzy To NPM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Setup for publication
        run: npm ci

      - name: Check if publishing enabled
        if: env.PUBLISH_ENABLED == 'true'
        run: echo "PUBLISH_ENABLED=true" >> $GITHUB_ENV
        
      - name: Publish to npm
        if: env.PUBLISH_ENABLED == 'true'
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
