name: Publish Vizzy as Node.js Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Check if publishing is enabled
      id: publish-check
      run: echo "PUBLISH_ENABLED=${{ secrets.PUBLISH_ENABLED }}" > $GITHUB_ENV

    - name: Publish to npm
      if: env.PUBLISH_ENABLED == 'true'
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
