name: Publish Vizzy To NPM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build Vizzy plugin
        run: npm run build

      - name: Check if publishing is enabled
        run: echo "PUBLISH_ENABLED=${{ secrets.PUBLISH_ENABLED }}" >> $GITHUB_ENV

      - name: Publish to npm
        if: env.PUBLISH_ENABLED == 'true'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
