name: Create Vizzy Release From Tag

on:
  push:
    tags:
      - 'v*.*.*' # This matches version tags like v1.0.0, v1.2.3, etc.

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Use the latest stable Node.js version

      - name: Get the latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "none")
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Extract current and previous minor versions
        id: extract_versions
        run: |
          current_tag=${GITHUB_REF##*/}
          current_minor_version=$(echo $current_tag | awk -F. '{print $2}')
          previous_tag=${{ env.latest_tag }}
          if [ "$previous_tag" != "none" ]; then
            previous_minor_version=$(echo $previous_tag | awk -F. '{print $2}')
          else
            previous_minor_version=-1
          fi

          echo "Current tag: $current_tag"
          echo "Previous tag: $previous_tag"

          echo "current_minor_version=$current_minor_version" >> $GITHUB_ENV
          echo "previous_minor_version=$previous_minor_version" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Install github_changelog_generator
        run: gem install github_changelog_generator

      - name: Generate changelog
        run: github_changelog_generator -u ${{ github.repository_owner }} -p ${{ github.event.repository.name }} --token ${{ secrets.GITHUB_TOKEN }}

      - name: Get the version from package.json
        id: get_version
        run: echo "version=$(node -p -e \"require('./package.json').version\")" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          body: |
            $(cat CHANGELOG.md)

      - name: Upload esm.js and .js files
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/vizzy.esm.js
          asset_name: vizzy.esm.js
          asset_content_type: application/javascript

      - name: Upload js files
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/vizzy.js
          asset_name: vizzy.js
          asset_content_type: application/javascript
